---
abstract: 'Cross-language event-driven ORM'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::Class: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel
requires:
  CPS: 0.10
  DateTime::Format::Duration: 0
  EntityModel::Class: 0.010
  JSON::XS: 2.00
  Mixin::Event::Dispatch: 0.002
  Module::Load: 0
  Template: 2.18
  XML::XPath: 1.00
version: 0.015
