---
abstract: 'Cross-language event-driven ORM'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::Class: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel
requires:
  CPS: 0.10
  DateTime::Format::Duration: 0
  EntityModel::Class: 0.011
  JSON::XS: 2.00
  Mixin::Event::Dispatch: 0.002
  Module::Load: 0
  Parser::MGC: 0.10
  Template: 2.18
  XML::XPath: 1.00
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=EntityModel
  homepage: http://search.cpan.org/dist/EntityModel/
version: 0.017
