---
abstract: 'Define and manage entities across languages'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::Class: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110350'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel
requires:
  Cache::Memcached::Fast: 0
  EntityModel::Class: 0.001
  EntityModel::Log: 0.001
  Module::Load: 0
  XML::XPath: 1.00
  perl: 5.010
version: 0.003
